language: java
dist: trusty
jdk:
  - oraclejdk8
cache:
  directories:
    - "$HOME/.cache"
script:
  - cd clarpse
  - mvn clean package assembly:single
after_success:
  - mvn deploy --settings ../settings.xml -Dmaven.install.skip=true
  - bash <(curl -s https://codecov.io/bash)
