language: java
cache:
  directories:
  - .autoconf
  - $HOME/.m2
jdk:
  - oraclejdk8
script: 
         - cd clarpse
         - mvn clean package assembly:single deploy --settings settings.xml
after_success:
         - bash <(curl -s https://codecov.io/bash)
